### PR TITLE
Generalized noun declension exercise - frontend (#658)

### PR DESCRIPTION
**Pull request by psfinaki**
This is the new page - I put the (beta) label that we can remove after removing "Noun Plurals" and "Noun Accusatives".

Together with the Server part looks like this:
image

### CODE REVIEW

**Comment by reflash** [comment]
How does it look on mobile? seems that the task message could be too long

**Comment by psfinaki** [comment]
Well, this is sort of the unlucky scenario:
image

Usually it fits. But I agree it would be nice to have some other control for that, this was just relatively easy to do, taking inspiration from conjugations.

If there is a simple way to make things better here, let's go for it, if not maybe we can take it separately...

**Comment by reflash** [comment]
> If there is a simple way to make things better here, let's go for it, if not maybe we can take it separately...

I think you could try overflowing the text on next line if it's too long, that could be a good workaround

**Comment by psfinaki** [comment]
Well so I tried something quick and dirty, namely adjusting the `Task` module:
```fsharp
let wrap (s: string) =
    let magicNumber = 22
    if s.Length < magicNumber
    then s
    else 
        let lastSpaceIndex = s.LastIndexOf(' ')
        s.Remove(lastSpaceIndex, 1).Insert(lastSpaceIndex, Environment.NewLine)
...
let word = if isMobile then wrap task.Word else task.Word
{ Word = str word; InputClass = inputClass; InputText = model.Input.Value }
```
But this does not seem to have any effect (although I verified replacement works).

Maybe should be [somehow solved via css](https://stackoverflow.com/questions/1199352/smart-way-to-truncate-long-strings)?

**Comment by reflash** [comment]
> Well so I tried something quick and dirty, namely adjusting the `Task` module:
> 
> ```fsharp
> let wrap (s: string) =
>     let magicNumber = 22
>     if s.Length < magicNumber
>     then s
>     else 
>         let lastSpaceIndex = s.LastIndexOf(' ')
>         s.Remove(lastSpaceIndex, 1).Insert(lastSpaceIndex, Environment.NewLine)
> ...
> let word = if isMobile then wrap task.Word else task.Word
> { Word = str word; InputClass = inputClass; InputText = model.Input.Value }
> ```
> 
> But this does not seem to have any effect (although I verified replacement works with other symbols).
> 
> Maybe should be [somehow solved via css](https://stackoverflow.com/questions/1199352/smart-way-to-truncate-long-strings)?

I think it could be solved via css. Afaik the gray block is of fixed width, so maybe if overflow is enabled for that it should wrap it on next line. maybe height shouldn't be fixed to a value, but rather set using min-height.

Anyway if this doesn't work it seems fine for now and we can fix it up later

**Comment by psfinaki** [comment]
Alright, I created an [issue](https://github.com/psfinaki/CheckYourCzech/issues/661) for that, we can address it later.

**Pull request merged**
